[package]
name = "wubwub"
version = "0.1.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]

[dependencies]
rocket = "0.3.14"
rocket_codegen = "0.3.14"
serde = "1.0"
serde_derive = "1.0"
sass-rs = "0.2.1"
comrak = { version = "0.2", default-features = false }

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]
