name: CI
on: [push, pull_request]
env:
  RUST_BACKTRACE: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        run: |
          # Install extra rustup components
          rustup component add rustfmt
          cargo fmt --all -- --check
      - name: Correct Nightly Version
        # Ensure everything is run and tested with the same nightly version
        run: ci/check-nightly-version.sh
      - name: Test
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          # Check if the code is good
          cargo build --all --locked
          cargo test --all --locked
